/**
 * applier.ts — Closes the loop from dream proposals to applied changes.
 *
 * RATIONALE
 * dream.ts produces proposals. Without an applier, those proposals sit in
 * latest.json forever — manually inspected at best, ignored at worst. This
 * module reads the latest dream report and applies one proposal at a time
 * via the matching mechanism for each proposal type:
 *
 *   skill       → scaffold a SKILL.md skeleton under ~/.pai/skills/
 *   isa         → append a Decision to the relevant project ISA
 *   algo-tune   → write to ~/.pai/data/algo-tuning.json (read by classifier)
 *   knowledge   → append to vault MEMORY.md (or specific KNOWLEDGE/ entry)
 *   extension   → just surface to the user (creating an extension is non-trivial)
 *   config      → just surface to the user (config changes need explicit ask)
 *
 * The applier ALSO maintains the auto-managed soul files:
 *   SHADOW.md       — written when correction signals cluster around a behavior
 *   CORRECTIONS.md  — appended whenever a high-confidence correction signal fires
 *   STORY.md        — appended at meta-reflection time with growth narrative
 *
 * Commands registered:
 *   /apply <proposal-id>           — apply one proposal from latest.json
 *   /apply auto                    — apply all proposals tagged auto-applicable
 *   /apply soul-refresh            — rebuild SHADOW/CORRECTIONS from signals.jsonl
 */

import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import {
	appendFileSync,
	existsSync,
	mkdirSync,
	readFileSync,
	writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { loadSignals, type SignalRecord } from "./signals.js";

// ── Paths ────────────────────────────────────────────────────────────────────

const DREAM_LATEST = join(homedir(), ".pi", "dreams", "latest.json");
const PAI_DATA = join(homedir(), ".pai", "data");
const ALGO_TUNING_FILE = join(PAI_DATA, "algo-tuning.json");
const APPLIER_LOG = join(PAI_DATA, "applier.jsonl");
const SKILLS_DIR = join(homedir(), ".pai", "skills");
const VAULT_PATH = process.env.VAULT_PATH ?? join(homedir(), "Developer", "knowledge-base");
const SHADOW_FILE = join(VAULT_PATH, "Atlas", "TELOS", "SHADOW.md");
const CORRECTIONS_FILE = join(VAULT_PATH, "Atlas", "TELOS", "CORRECTIONS.md");
const STORY_FILE = join(VAULT_PATH, "Atlas", "TELOS", "STORY.md");
const VAULT_MEMORY = join(VAULT_PATH, "MEMORY.md");

// ── Types ────────────────────────────────────────────────────────────────────

interface DreamProposal {
	id: string;
	type: "skill" | "isa" | "algo-tune" | "knowledge" | "extension" | "config";
	title: string;
	description: string;
	evidence: string[];
	effort: "trivial" | "small" | "medium" | "large";
	priority: "high" | "medium" | "low";
	action?: string;
	auto_applicable?: boolean;
}

interface DreamReport {
	timestamp: string;
	proposals: DreamProposal[];
	applied: string[];
}

interface AlgoTuning {
	tier_overrides?: Array<{ pattern: string; tier: string; reason: string }>;
	updated: string;
	revisions: number;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function ensureDir(path: string): void {
	try { mkdirSync(path, { recursive: true }); } catch {}
}

function logApplied(entry: Record<string, unknown>): void {
	ensureDir(PAI_DATA);
	try {
		appendFileSync(APPLIER_LOG, JSON.stringify({ ...entry, ts: new Date().toISOString() }) + "\n");
	} catch {}
}

function readReport(): DreamReport | null {
	if (!existsSync(DREAM_LATEST)) return null;
	try {
		return JSON.parse(readFileSync(DREAM_LATEST, "utf-8")) as DreamReport;
	} catch {
		return null;
	}
}

function writeReport(report: DreamReport): void {
	try {
		writeFileSync(DREAM_LATEST, JSON.stringify(report, null, 2));
	} catch {}
}

// ── Per-type appliers ────────────────────────────────────────────────────────

function applySkill(p: DreamProposal): { ok: boolean; detail: string } {
	if (!p.action) return { ok: false, detail: "skill proposal missing `action` body" };
	const slug = p.title
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/^-+|-+$/g, "")
		.slice(0, 40);
	const skillDir = join(SKILLS_DIR, slug);
	const skillMd = join(skillDir, "SKILL.md");
	if (existsSync(skillMd)) {
		return { ok: false, detail: `skill already exists at ${skillMd}` };
	}
	ensureDir(skillDir);
	const body = [
		"---",
		`name: ${slug}`,
		`description: |`,
		`  ${p.description.split("\n").join("\n  ")}`,
		`  Generated by dream.applier on ${new Date().toISOString()} from ${p.evidence.length} evidence items.`,
		"---",
		"",
		`# ${p.title}`,
		"",
		"## Purpose",
		p.description,
		"",
		"## Evidence",
		...p.evidence.map((e) => `- ${e}`),
		"",
		"## Action",
		p.action ?? "(no action specified)",
		"",
		"## Status",
		`scaffolded — review and refine before relying on it.`,
	].join("\n");
	try {
		writeFileSync(skillMd, body);
		return { ok: true, detail: `scaffolded ${skillMd}` };
	} catch (err) {
		return { ok: false, detail: `write failed: ${(err as Error).message}` };
	}
}

function applyIsa(p: DreamProposal, cwd: string): { ok: boolean; detail: string } {
	if (!p.action) return { ok: false, detail: "isa proposal missing `action`" };
	const isaPath = join(cwd, ".pi", "ISA.md");
	if (!existsSync(isaPath)) {
		return { ok: false, detail: `no ISA at ${isaPath} — run isa_scaffold first` };
	}
	const decision = `- ${new Date().toISOString()} — applied: ${p.title}. Why: ${p.description.slice(0, 200)}.`;
	try {
		const cur = readFileSync(isaPath, "utf-8");
		// Append to ## Decisions section if present, else append at end.
		let updated: string;
		const decIdx = cur.search(/^##\s+Decisions\s*$/m);
		if (decIdx >= 0) {
			const tail = cur.slice(decIdx);
			const nextHeaderIdx = tail.search(/\n##\s+\S/);
			const insertAt = nextHeaderIdx >= 0 ? decIdx + nextHeaderIdx : cur.length;
			updated = cur.slice(0, insertAt) + (cur.slice(0, insertAt).endsWith("\n") ? "" : "\n") + decision + "\n" + cur.slice(insertAt);
		} else {
			updated = cur + (cur.endsWith("\n") ? "" : "\n") + "\n## Decisions\n\n" + decision + "\n";
		}
		writeFileSync(isaPath, updated);
		return { ok: true, detail: `appended Decision to ${isaPath}` };
	} catch (err) {
		return { ok: false, detail: `write failed: ${(err as Error).message}` };
	}
}

function applyAlgoTune(p: DreamProposal): { ok: boolean; detail: string } {
	if (!p.action) return { ok: false, detail: "algo-tune missing `action`" };

	let cur: AlgoTuning;
	if (existsSync(ALGO_TUNING_FILE)) {
		try { cur = JSON.parse(readFileSync(ALGO_TUNING_FILE, "utf-8")) as AlgoTuning; }
		catch { cur = { tier_overrides: [], updated: "", revisions: 0 }; }
	} else {
		cur = { tier_overrides: [], updated: "", revisions: 0 };
	}

	// Expect action of shape "pattern=<regex>; tier=<eN>; reason=<text>" — flexible parse
	const patternMatch = p.action.match(/pattern\s*=\s*"?([^";]+)"?/);
	const tierMatch = p.action.match(/tier\s*=\s*(e[1-5])/i);
	const reasonMatch = p.action.match(/reason\s*=\s*"?([^"]+)"?$/);
	if (!patternMatch || !tierMatch) {
		return { ok: false, detail: `algo-tune action missing pattern= or tier=: "${p.action}"` };
	}

	cur.tier_overrides = cur.tier_overrides ?? [];
	cur.tier_overrides.push({
		pattern: patternMatch[1].trim(),
		tier: tierMatch[1].toLowerCase(),
		reason: reasonMatch?.[1] ?? p.title,
	});
	cur.updated = new Date().toISOString();
	cur.revisions = (cur.revisions ?? 0) + 1;

	ensureDir(PAI_DATA);
	try {
		writeFileSync(ALGO_TUNING_FILE, JSON.stringify(cur, null, 2));
		return { ok: true, detail: `appended override; total=${cur.tier_overrides.length}` };
	} catch (err) {
		return { ok: false, detail: `write failed: ${(err as Error).message}` };
	}
}

function applyKnowledge(p: DreamProposal): { ok: boolean; detail: string } {
	if (!existsSync(VAULT_PATH)) {
		return { ok: false, detail: `vault not present at ${VAULT_PATH}` };
	}
	const entry = [
		"",
		`### ${p.title}`,
		`*Captured by dream on ${new Date().toISOString().slice(0, 10)} — priority ${p.priority}*`,
		"",
		p.description,
		"",
		"Evidence:",
		...p.evidence.map((e) => `- ${e}`),
	].join("\n");
	try {
		appendFileSync(VAULT_MEMORY, entry + "\n");
		return { ok: true, detail: `appended to ${VAULT_MEMORY}` };
	} catch (err) {
		return { ok: false, detail: `write failed: ${(err as Error).message}` };
	}
}

function applyOne(p: DreamProposal, cwd: string): { ok: boolean; detail: string } {
	switch (p.type) {
		case "skill": return applySkill(p);
		case "isa": return applyIsa(p, cwd);
		case "algo-tune": return applyAlgoTune(p);
		case "knowledge": return applyKnowledge(p);
		case "extension":
		case "config":
			return { ok: false, detail: `${p.type} proposals require manual implementation — surfacing only` };
	}
}

// ── Soul-file refresh (SHADOW / CORRECTIONS) ─────────────────────────────────

function clusterCorrections(signals: SignalRecord[]): Map<string, SignalRecord[]> {
	const clusters = new Map<string, SignalRecord[]>();
	for (const s of signals) {
		if (s.kind !== "correction" && s.kind !== "frustration") continue;
		// Cluster by evidence pattern — "negation+halt" goes together.
		const key = s.evidence;
		const cur = clusters.get(key) ?? [];
		cur.push(s);
		clusters.set(key, cur);
	}
	return clusters;
}

function refreshCorrections(): { ok: boolean; detail: string } {
	if (!existsSync(VAULT_PATH)) return { ok: false, detail: `vault not present at ${VAULT_PATH}` };
	const signals = loadSignals();
	if (signals.length === 0) return { ok: true, detail: "no signals yet" };

	const clusters = clusterCorrections(signals);
	const lines: string[] = [
		"# CORRECTIONS",
		"",
		"*Auto-managed by pi pai extension's signal-extraction loop. Do not hand-edit clusters — but you may rewrite the prose summaries and Lars-side reflections.*",
		"",
		`Last refresh: ${new Date().toISOString()}`,
		`Total correction/frustration signals: ${[...clusters.values()].reduce((s, l) => s + l.length, 0)}`,
		"",
	];

	const sorted = [...clusters.entries()].sort((a, b) => b[1].length - a[1].length);
	for (const [evidence, items] of sorted) {
		const last = items[items.length - 1];
		lines.push(`## ${evidence} (${items.length})`);
		lines.push("");
		lines.push(`Latest example (${last.ts.slice(0, 10)}):`);
		lines.push(`> ${last.prompt_excerpt.slice(0, 240)}`);
		lines.push("");
	}

	ensureDir(join(VAULT_PATH, "Atlas", "TELOS"));
	try {
		writeFileSync(CORRECTIONS_FILE, lines.join("\n"));
		return { ok: true, detail: `wrote ${CORRECTIONS_FILE} with ${clusters.size} clusters` };
	} catch (err) {
		return { ok: false, detail: `write failed: ${(err as Error).message}` };
	}
}

function refreshShadow(): { ok: boolean; detail: string } {
	if (!existsSync(VAULT_PATH)) return { ok: false, detail: `vault not present at ${VAULT_PATH}` };
	const signals = loadSignals();
	const corrections = signals.filter((s) => s.kind === "correction" || s.kind === "frustration");
	if (corrections.length === 0) return { ok: true, detail: "no shadow material yet" };

	const evidenceTallies = new Map<string, number>();
	for (const c of corrections) {
		for (const ev of c.evidence.split(",")) {
			evidenceTallies.set(ev, (evidenceTallies.get(ev) || 0) + 1);
		}
	}
	const top = [...evidenceTallies.entries()].sort((a, b) => b[1] - a[1]).slice(0, 8);

	const lines: string[] = [
		"# SHADOW",
		"",
		"*Behavioral tendencies pi has observed in the assistant — patterns that produced corrections or frustration. Surfaced into the system prompt so the assistant can self-monitor in real time.*",
		"",
		`Last refresh: ${new Date().toISOString()}`,
		`Sample size: ${corrections.length} correction/frustration signals.`,
		"",
		"## Recurring patterns to watch",
		"",
	];
	for (const [pattern, count] of top) {
		lines.push(`- **${pattern}** — ${count} occurrence${count === 1 ? "" : "s"}`);
	}
	lines.push("");
	lines.push("## What to do when you catch yourself in one of these");
	lines.push("");
	lines.push("- Stop. Restate what Lars actually asked for verbatim before continuing.");
	lines.push("- If the pattern is `negation` or `halt`, the previous turn likely violated a stated preference — re-read it for the missed constraint.");
	lines.push("- If the pattern is `still-broken` or `lament`, the same fix has been tried twice. Stop reapplying it. Surface the impasse and ask.");

	ensureDir(join(VAULT_PATH, "Atlas", "TELOS"));
	try {
		writeFileSync(SHADOW_FILE, lines.join("\n"));
		return { ok: true, detail: `wrote ${SHADOW_FILE} with ${top.length} top patterns` };
	} catch (err) {
		return { ok: false, detail: `write failed: ${(err as Error).message}` };
	}
}

function appendStory(narrative: string): { ok: boolean; detail: string } {
	if (!existsSync(VAULT_PATH)) return { ok: false, detail: `vault not present at ${VAULT_PATH}` };
	ensureDir(join(VAULT_PATH, "Atlas", "TELOS"));
	const header = existsSync(STORY_FILE) ? "" : "# STORY\n\n*Chronological growth log written by pi at meta-reflection time.*\n\n";
	const entry = `## ${new Date().toISOString().slice(0, 10)}\n\n${narrative}\n\n`;
	try {
		appendFileSync(STORY_FILE, header + entry);
		return { ok: true, detail: `appended to ${STORY_FILE}` };
	} catch (err) {
		return { ok: false, detail: `write failed: ${(err as Error).message}` };
	}
}

// ── Public API + commands ───────────────────────────────────────────────────

export function applyProposalById(id: string, cwd: string): { ok: boolean; detail: string } {
	const report = readReport();
	if (!report) return { ok: false, detail: "no dream report — run /dream first" };
	const proposal = report.proposals.find((p) => p.id === id);
	if (!proposal) return { ok: false, detail: `proposal id "${id}" not found in latest dream` };
	if (report.applied?.includes(id)) return { ok: false, detail: `already applied: ${id}` };

	const result = applyOne(proposal, cwd);
	logApplied({ id, type: proposal.type, ok: result.ok, detail: result.detail });
	if (result.ok) {
		report.applied = report.applied ?? [];
		report.applied.push(id);
		writeReport(report);
	}
	return result;
}

export function applyAllAutoApplicable(cwd: string): { ok: boolean; applied: string[]; failed: string[] } {
	const report = readReport();
	if (!report) return { ok: false, applied: [], failed: [] };
	const applied: string[] = [];
	const failed: string[] = [];
	for (const p of report.proposals) {
		if (!p.auto_applicable) continue;
		if (report.applied?.includes(p.id)) continue;
		const result = applyOne(p, cwd);
		logApplied({ id: p.id, type: p.type, ok: result.ok, detail: result.detail, batch: true });
		if (result.ok) applied.push(p.id);
		else failed.push(`${p.id}: ${result.detail}`);
	}
	if (applied.length) {
		report.applied = (report.applied ?? []).concat(applied);
		writeReport(report);
	}
	return { ok: failed.length === 0, applied, failed };
}

export function refreshSoulFiles(): { corrections: string; shadow: string } {
	const c = refreshCorrections();
	const s = refreshShadow();
	return { corrections: c.detail, shadow: s.detail };
}

export function registerApplier(pi: ExtensionAPI): void {
	pi.registerCommand("apply", {
		description: "Apply dream proposals or refresh soul files. Args: <proposal-id> | auto | soul-refresh | story <narrative>",
		handler: async (args, ctx) => {
			const arg = (args ?? "").trim();
			const cwd = ctx?.cwd ?? process.cwd();

			if (!arg || arg === "list") {
				const report = readReport();
				if (!report) {
					ctx.ui.notify("No dream report. Run /dream first.", "info");
					return;
				}
				const lines = [`${report.proposals.length} proposals (${report.applied?.length ?? 0} applied):`];
				for (const p of report.proposals) {
					const status = report.applied?.includes(p.id) ? "✓" : "○";
					const auto = p.auto_applicable ? " [auto]" : "";
					lines.push(`${status} ${p.id} [${p.type}, ${p.priority}]${auto}: ${p.title}`);
				}
				ctx.ui.notify(lines.join("\n"), "info");
				return;
			}

			if (arg === "auto") {
				const result = applyAllAutoApplicable(cwd);
				const msg = `Auto-apply: ${result.applied.length} applied, ${result.failed.length} failed.\n${result.applied.join(", ")}` +
					(result.failed.length ? `\nFailed:\n${result.failed.join("\n")}` : "");
				ctx.ui.notify(msg, result.ok ? "info" : "warning");
				return;
			}

			if (arg === "soul-refresh") {
				const r = refreshSoulFiles();
				ctx.ui.notify(`Soul refresh:\n  corrections: ${r.corrections}\n  shadow: ${r.shadow}`, "info");
				return;
			}

			if (arg.startsWith("story ")) {
				const narrative = arg.slice("story ".length).trim();
				if (!narrative) {
					ctx.ui.notify("usage: /apply story <narrative>", "warning");
					return;
				}
				const r = appendStory(narrative);
				ctx.ui.notify(r.detail, r.ok ? "info" : "warning");
				return;
			}

			// Treat as proposal ID
			const result = applyProposalById(arg, cwd);
			ctx.ui.notify(`/apply ${arg}: ${result.detail}`, result.ok ? "info" : "warning");
		},
	});

	// Auto-refresh soul files on every Nth signal — bounded by signal count
	// so we don't write to the vault on every turn.
	let lastSignalCount = 0;
	pi.on("agent_end", async () => {
		const signals = loadSignals();
		if (signals.length === 0) return;
		// Refresh every 10 new signals after the first 5
		if (signals.length >= 5 && signals.length - lastSignalCount >= 10) {
			refreshShadow();
			refreshCorrections();
			lastSignalCount = signals.length;
		}
	});
}
